/*
Deepfence ThreatMapper

Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.

API version: 2.0.0
Contact: community@deepfence.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ReportersOrderFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReportersOrderFilter{}

// ReportersOrderFilter struct for ReportersOrderFilter
type ReportersOrderFilter struct {
	OrderBy string `json:"order_by"`
	OrderFields []string `json:"order_fields"`
}

// NewReportersOrderFilter instantiates a new ReportersOrderFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReportersOrderFilter(orderBy string, orderFields []string) *ReportersOrderFilter {
	this := ReportersOrderFilter{}
	this.OrderBy = orderBy
	this.OrderFields = orderFields
	return &this
}

// NewReportersOrderFilterWithDefaults instantiates a new ReportersOrderFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReportersOrderFilterWithDefaults() *ReportersOrderFilter {
	this := ReportersOrderFilter{}
	return &this
}

// GetOrderBy returns the OrderBy field value
func (o *ReportersOrderFilter) GetOrderBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderBy
}

// GetOrderByOk returns a tuple with the OrderBy field value
// and a boolean to check if the value has been set.
func (o *ReportersOrderFilter) GetOrderByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderBy, true
}

// SetOrderBy sets field value
func (o *ReportersOrderFilter) SetOrderBy(v string) {
	o.OrderBy = v
}

// GetOrderFields returns the OrderFields field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *ReportersOrderFilter) GetOrderFields() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.OrderFields
}

// GetOrderFieldsOk returns a tuple with the OrderFields field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReportersOrderFilter) GetOrderFieldsOk() ([]string, bool) {
	if o == nil || IsNil(o.OrderFields) {
		return nil, false
	}
	return o.OrderFields, true
}

// SetOrderFields sets field value
func (o *ReportersOrderFilter) SetOrderFields(v []string) {
	o.OrderFields = v
}

func (o ReportersOrderFilter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReportersOrderFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["order_by"] = o.OrderBy
	if o.OrderFields != nil {
		toSerialize["order_fields"] = o.OrderFields
	}
	return toSerialize, nil
}

type NullableReportersOrderFilter struct {
	value *ReportersOrderFilter
	isSet bool
}

func (v NullableReportersOrderFilter) Get() *ReportersOrderFilter {
	return v.value
}

func (v *NullableReportersOrderFilter) Set(val *ReportersOrderFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableReportersOrderFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableReportersOrderFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReportersOrderFilter(val *ReportersOrderFilter) *NullableReportersOrderFilter {
	return &NullableReportersOrderFilter{value: val, isSet: true}
}

func (v NullableReportersOrderFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReportersOrderFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


