/*
Deepfence ThreatMapper

Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.

API version: 2.0.0
Contact: community@deepfence.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ModelComplianceScanTriggerReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelComplianceScanTriggerReq{}

// ModelComplianceScanTriggerReq struct for ModelComplianceScanTriggerReq
type ModelComplianceScanTriggerReq struct {
	ScanTriggers []ModelComplianceScanTrigger `json:"scan_triggers"`
}

// NewModelComplianceScanTriggerReq instantiates a new ModelComplianceScanTriggerReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelComplianceScanTriggerReq(scanTriggers []ModelComplianceScanTrigger) *ModelComplianceScanTriggerReq {
	this := ModelComplianceScanTriggerReq{}
	this.ScanTriggers = scanTriggers
	return &this
}

// NewModelComplianceScanTriggerReqWithDefaults instantiates a new ModelComplianceScanTriggerReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelComplianceScanTriggerReqWithDefaults() *ModelComplianceScanTriggerReq {
	this := ModelComplianceScanTriggerReq{}
	return &this
}

// GetScanTriggers returns the ScanTriggers field value
// If the value is explicit nil, the zero value for []ModelComplianceScanTrigger will be returned
func (o *ModelComplianceScanTriggerReq) GetScanTriggers() []ModelComplianceScanTrigger {
	if o == nil {
		var ret []ModelComplianceScanTrigger
		return ret
	}

	return o.ScanTriggers
}

// GetScanTriggersOk returns a tuple with the ScanTriggers field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelComplianceScanTriggerReq) GetScanTriggersOk() ([]ModelComplianceScanTrigger, bool) {
	if o == nil || isNil(o.ScanTriggers) {
		return nil, false
	}
	return o.ScanTriggers, true
}

// SetScanTriggers sets field value
func (o *ModelComplianceScanTriggerReq) SetScanTriggers(v []ModelComplianceScanTrigger) {
	o.ScanTriggers = v
}

func (o ModelComplianceScanTriggerReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelComplianceScanTriggerReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ScanTriggers != nil {
		toSerialize["scan_triggers"] = o.ScanTriggers
	}
	return toSerialize, nil
}

type NullableModelComplianceScanTriggerReq struct {
	value *ModelComplianceScanTriggerReq
	isSet bool
}

func (v NullableModelComplianceScanTriggerReq) Get() *ModelComplianceScanTriggerReq {
	return v.value
}

func (v *NullableModelComplianceScanTriggerReq) Set(val *ModelComplianceScanTriggerReq) {
	v.value = val
	v.isSet = true
}

func (v NullableModelComplianceScanTriggerReq) IsSet() bool {
	return v.isSet
}

func (v *NullableModelComplianceScanTriggerReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelComplianceScanTriggerReq(val *ModelComplianceScanTriggerReq) *NullableModelComplianceScanTriggerReq {
	return &NullableModelComplianceScanTriggerReq{value: val, isSet: true}
}

func (v NullableModelComplianceScanTriggerReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelComplianceScanTriggerReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


