/*
Deepfence ThreatMapper

Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.

API version: 2.0.0
Contact: community@deepfence.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ModelHost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelHost{}

// ModelHost struct for ModelHost
type ModelHost struct {
	CloudMetadata map[string]interface{} `json:"cloud_metadata"`
	ComplianceScanStatus *string `json:"compliance_scan_status,omitempty"`
	CompliancesCount *int32 `json:"compliances_count,omitempty"`
	ContainerImages []ModelContainerImage `json:"container_images"`
	Containers []ModelContainer `json:"containers"`
	HostName string `json:"host_name"`
	MalwareScanStatus *string `json:"malware_scan_status,omitempty"`
	MalwaresCount *int32 `json:"malwares_count,omitempty"`
	Metrics ModelComputeMetrics `json:"metrics"`
	NodeId string `json:"node_id"`
	Pods []ModelPod `json:"pods"`
	Processes []ModelProcess `json:"processes"`
	SecretScanStatus *string `json:"secret_scan_status,omitempty"`
	SecretsCount *int32 `json:"secrets_count,omitempty"`
	VulnerabilitiesCount *int32 `json:"vulnerabilities_count,omitempty"`
	VulnerabilityScanStatus *string `json:"vulnerability_scan_status,omitempty"`
}

// NewModelHost instantiates a new ModelHost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelHost(cloudMetadata map[string]interface{}, containerImages []ModelContainerImage, containers []ModelContainer, hostName string, metrics ModelComputeMetrics, nodeId string, pods []ModelPod, processes []ModelProcess) *ModelHost {
	this := ModelHost{}
	this.CloudMetadata = cloudMetadata
	this.ContainerImages = containerImages
	this.Containers = containers
	this.HostName = hostName
	this.Metrics = metrics
	this.NodeId = nodeId
	this.Pods = pods
	this.Processes = processes
	return &this
}

// NewModelHostWithDefaults instantiates a new ModelHost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelHostWithDefaults() *ModelHost {
	this := ModelHost{}
	return &this
}

// GetCloudMetadata returns the CloudMetadata field value
func (o *ModelHost) GetCloudMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.CloudMetadata
}

// GetCloudMetadataOk returns a tuple with the CloudMetadata field value
// and a boolean to check if the value has been set.
func (o *ModelHost) GetCloudMetadataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.CloudMetadata, true
}

// SetCloudMetadata sets field value
func (o *ModelHost) SetCloudMetadata(v map[string]interface{}) {
	o.CloudMetadata = v
}

// GetComplianceScanStatus returns the ComplianceScanStatus field value if set, zero value otherwise.
func (o *ModelHost) GetComplianceScanStatus() string {
	if o == nil || IsNil(o.ComplianceScanStatus) {
		var ret string
		return ret
	}
	return *o.ComplianceScanStatus
}

// GetComplianceScanStatusOk returns a tuple with the ComplianceScanStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelHost) GetComplianceScanStatusOk() (*string, bool) {
	if o == nil || IsNil(o.ComplianceScanStatus) {
		return nil, false
	}
	return o.ComplianceScanStatus, true
}

// HasComplianceScanStatus returns a boolean if a field has been set.
func (o *ModelHost) HasComplianceScanStatus() bool {
	if o != nil && !IsNil(o.ComplianceScanStatus) {
		return true
	}

	return false
}

// SetComplianceScanStatus gets a reference to the given string and assigns it to the ComplianceScanStatus field.
func (o *ModelHost) SetComplianceScanStatus(v string) {
	o.ComplianceScanStatus = &v
}

// GetCompliancesCount returns the CompliancesCount field value if set, zero value otherwise.
func (o *ModelHost) GetCompliancesCount() int32 {
	if o == nil || IsNil(o.CompliancesCount) {
		var ret int32
		return ret
	}
	return *o.CompliancesCount
}

// GetCompliancesCountOk returns a tuple with the CompliancesCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelHost) GetCompliancesCountOk() (*int32, bool) {
	if o == nil || IsNil(o.CompliancesCount) {
		return nil, false
	}
	return o.CompliancesCount, true
}

// HasCompliancesCount returns a boolean if a field has been set.
func (o *ModelHost) HasCompliancesCount() bool {
	if o != nil && !IsNil(o.CompliancesCount) {
		return true
	}

	return false
}

// SetCompliancesCount gets a reference to the given int32 and assigns it to the CompliancesCount field.
func (o *ModelHost) SetCompliancesCount(v int32) {
	o.CompliancesCount = &v
}

// GetContainerImages returns the ContainerImages field value
// If the value is explicit nil, the zero value for []ModelContainerImage will be returned
func (o *ModelHost) GetContainerImages() []ModelContainerImage {
	if o == nil {
		var ret []ModelContainerImage
		return ret
	}

	return o.ContainerImages
}

// GetContainerImagesOk returns a tuple with the ContainerImages field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelHost) GetContainerImagesOk() ([]ModelContainerImage, bool) {
	if o == nil || IsNil(o.ContainerImages) {
		return nil, false
	}
	return o.ContainerImages, true
}

// SetContainerImages sets field value
func (o *ModelHost) SetContainerImages(v []ModelContainerImage) {
	o.ContainerImages = v
}

// GetContainers returns the Containers field value
// If the value is explicit nil, the zero value for []ModelContainer will be returned
func (o *ModelHost) GetContainers() []ModelContainer {
	if o == nil {
		var ret []ModelContainer
		return ret
	}

	return o.Containers
}

// GetContainersOk returns a tuple with the Containers field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelHost) GetContainersOk() ([]ModelContainer, bool) {
	if o == nil || IsNil(o.Containers) {
		return nil, false
	}
	return o.Containers, true
}

// SetContainers sets field value
func (o *ModelHost) SetContainers(v []ModelContainer) {
	o.Containers = v
}

// GetHostName returns the HostName field value
func (o *ModelHost) GetHostName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HostName
}

// GetHostNameOk returns a tuple with the HostName field value
// and a boolean to check if the value has been set.
func (o *ModelHost) GetHostNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HostName, true
}

// SetHostName sets field value
func (o *ModelHost) SetHostName(v string) {
	o.HostName = v
}

// GetMalwareScanStatus returns the MalwareScanStatus field value if set, zero value otherwise.
func (o *ModelHost) GetMalwareScanStatus() string {
	if o == nil || IsNil(o.MalwareScanStatus) {
		var ret string
		return ret
	}
	return *o.MalwareScanStatus
}

// GetMalwareScanStatusOk returns a tuple with the MalwareScanStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelHost) GetMalwareScanStatusOk() (*string, bool) {
	if o == nil || IsNil(o.MalwareScanStatus) {
		return nil, false
	}
	return o.MalwareScanStatus, true
}

// HasMalwareScanStatus returns a boolean if a field has been set.
func (o *ModelHost) HasMalwareScanStatus() bool {
	if o != nil && !IsNil(o.MalwareScanStatus) {
		return true
	}

	return false
}

// SetMalwareScanStatus gets a reference to the given string and assigns it to the MalwareScanStatus field.
func (o *ModelHost) SetMalwareScanStatus(v string) {
	o.MalwareScanStatus = &v
}

// GetMalwaresCount returns the MalwaresCount field value if set, zero value otherwise.
func (o *ModelHost) GetMalwaresCount() int32 {
	if o == nil || IsNil(o.MalwaresCount) {
		var ret int32
		return ret
	}
	return *o.MalwaresCount
}

// GetMalwaresCountOk returns a tuple with the MalwaresCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelHost) GetMalwaresCountOk() (*int32, bool) {
	if o == nil || IsNil(o.MalwaresCount) {
		return nil, false
	}
	return o.MalwaresCount, true
}

// HasMalwaresCount returns a boolean if a field has been set.
func (o *ModelHost) HasMalwaresCount() bool {
	if o != nil && !IsNil(o.MalwaresCount) {
		return true
	}

	return false
}

// SetMalwaresCount gets a reference to the given int32 and assigns it to the MalwaresCount field.
func (o *ModelHost) SetMalwaresCount(v int32) {
	o.MalwaresCount = &v
}

// GetMetrics returns the Metrics field value
func (o *ModelHost) GetMetrics() ModelComputeMetrics {
	if o == nil {
		var ret ModelComputeMetrics
		return ret
	}

	return o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value
// and a boolean to check if the value has been set.
func (o *ModelHost) GetMetricsOk() (*ModelComputeMetrics, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metrics, true
}

// SetMetrics sets field value
func (o *ModelHost) SetMetrics(v ModelComputeMetrics) {
	o.Metrics = v
}

// GetNodeId returns the NodeId field value
func (o *ModelHost) GetNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value
// and a boolean to check if the value has been set.
func (o *ModelHost) GetNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeId, true
}

// SetNodeId sets field value
func (o *ModelHost) SetNodeId(v string) {
	o.NodeId = v
}

// GetPods returns the Pods field value
// If the value is explicit nil, the zero value for []ModelPod will be returned
func (o *ModelHost) GetPods() []ModelPod {
	if o == nil {
		var ret []ModelPod
		return ret
	}

	return o.Pods
}

// GetPodsOk returns a tuple with the Pods field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelHost) GetPodsOk() ([]ModelPod, bool) {
	if o == nil || IsNil(o.Pods) {
		return nil, false
	}
	return o.Pods, true
}

// SetPods sets field value
func (o *ModelHost) SetPods(v []ModelPod) {
	o.Pods = v
}

// GetProcesses returns the Processes field value
// If the value is explicit nil, the zero value for []ModelProcess will be returned
func (o *ModelHost) GetProcesses() []ModelProcess {
	if o == nil {
		var ret []ModelProcess
		return ret
	}

	return o.Processes
}

// GetProcessesOk returns a tuple with the Processes field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelHost) GetProcessesOk() ([]ModelProcess, bool) {
	if o == nil || IsNil(o.Processes) {
		return nil, false
	}
	return o.Processes, true
}

// SetProcesses sets field value
func (o *ModelHost) SetProcesses(v []ModelProcess) {
	o.Processes = v
}

// GetSecretScanStatus returns the SecretScanStatus field value if set, zero value otherwise.
func (o *ModelHost) GetSecretScanStatus() string {
	if o == nil || IsNil(o.SecretScanStatus) {
		var ret string
		return ret
	}
	return *o.SecretScanStatus
}

// GetSecretScanStatusOk returns a tuple with the SecretScanStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelHost) GetSecretScanStatusOk() (*string, bool) {
	if o == nil || IsNil(o.SecretScanStatus) {
		return nil, false
	}
	return o.SecretScanStatus, true
}

// HasSecretScanStatus returns a boolean if a field has been set.
func (o *ModelHost) HasSecretScanStatus() bool {
	if o != nil && !IsNil(o.SecretScanStatus) {
		return true
	}

	return false
}

// SetSecretScanStatus gets a reference to the given string and assigns it to the SecretScanStatus field.
func (o *ModelHost) SetSecretScanStatus(v string) {
	o.SecretScanStatus = &v
}

// GetSecretsCount returns the SecretsCount field value if set, zero value otherwise.
func (o *ModelHost) GetSecretsCount() int32 {
	if o == nil || IsNil(o.SecretsCount) {
		var ret int32
		return ret
	}
	return *o.SecretsCount
}

// GetSecretsCountOk returns a tuple with the SecretsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelHost) GetSecretsCountOk() (*int32, bool) {
	if o == nil || IsNil(o.SecretsCount) {
		return nil, false
	}
	return o.SecretsCount, true
}

// HasSecretsCount returns a boolean if a field has been set.
func (o *ModelHost) HasSecretsCount() bool {
	if o != nil && !IsNil(o.SecretsCount) {
		return true
	}

	return false
}

// SetSecretsCount gets a reference to the given int32 and assigns it to the SecretsCount field.
func (o *ModelHost) SetSecretsCount(v int32) {
	o.SecretsCount = &v
}

// GetVulnerabilitiesCount returns the VulnerabilitiesCount field value if set, zero value otherwise.
func (o *ModelHost) GetVulnerabilitiesCount() int32 {
	if o == nil || IsNil(o.VulnerabilitiesCount) {
		var ret int32
		return ret
	}
	return *o.VulnerabilitiesCount
}

// GetVulnerabilitiesCountOk returns a tuple with the VulnerabilitiesCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelHost) GetVulnerabilitiesCountOk() (*int32, bool) {
	if o == nil || IsNil(o.VulnerabilitiesCount) {
		return nil, false
	}
	return o.VulnerabilitiesCount, true
}

// HasVulnerabilitiesCount returns a boolean if a field has been set.
func (o *ModelHost) HasVulnerabilitiesCount() bool {
	if o != nil && !IsNil(o.VulnerabilitiesCount) {
		return true
	}

	return false
}

// SetVulnerabilitiesCount gets a reference to the given int32 and assigns it to the VulnerabilitiesCount field.
func (o *ModelHost) SetVulnerabilitiesCount(v int32) {
	o.VulnerabilitiesCount = &v
}

// GetVulnerabilityScanStatus returns the VulnerabilityScanStatus field value if set, zero value otherwise.
func (o *ModelHost) GetVulnerabilityScanStatus() string {
	if o == nil || IsNil(o.VulnerabilityScanStatus) {
		var ret string
		return ret
	}
	return *o.VulnerabilityScanStatus
}

// GetVulnerabilityScanStatusOk returns a tuple with the VulnerabilityScanStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelHost) GetVulnerabilityScanStatusOk() (*string, bool) {
	if o == nil || IsNil(o.VulnerabilityScanStatus) {
		return nil, false
	}
	return o.VulnerabilityScanStatus, true
}

// HasVulnerabilityScanStatus returns a boolean if a field has been set.
func (o *ModelHost) HasVulnerabilityScanStatus() bool {
	if o != nil && !IsNil(o.VulnerabilityScanStatus) {
		return true
	}

	return false
}

// SetVulnerabilityScanStatus gets a reference to the given string and assigns it to the VulnerabilityScanStatus field.
func (o *ModelHost) SetVulnerabilityScanStatus(v string) {
	o.VulnerabilityScanStatus = &v
}

func (o ModelHost) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelHost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cloud_metadata"] = o.CloudMetadata
	if !IsNil(o.ComplianceScanStatus) {
		toSerialize["compliance_scan_status"] = o.ComplianceScanStatus
	}
	if !IsNil(o.CompliancesCount) {
		toSerialize["compliances_count"] = o.CompliancesCount
	}
	if o.ContainerImages != nil {
		toSerialize["container_images"] = o.ContainerImages
	}
	if o.Containers != nil {
		toSerialize["containers"] = o.Containers
	}
	toSerialize["host_name"] = o.HostName
	if !IsNil(o.MalwareScanStatus) {
		toSerialize["malware_scan_status"] = o.MalwareScanStatus
	}
	if !IsNil(o.MalwaresCount) {
		toSerialize["malwares_count"] = o.MalwaresCount
	}
	toSerialize["metrics"] = o.Metrics
	toSerialize["node_id"] = o.NodeId
	if o.Pods != nil {
		toSerialize["pods"] = o.Pods
	}
	if o.Processes != nil {
		toSerialize["processes"] = o.Processes
	}
	if !IsNil(o.SecretScanStatus) {
		toSerialize["secret_scan_status"] = o.SecretScanStatus
	}
	if !IsNil(o.SecretsCount) {
		toSerialize["secrets_count"] = o.SecretsCount
	}
	if !IsNil(o.VulnerabilitiesCount) {
		toSerialize["vulnerabilities_count"] = o.VulnerabilitiesCount
	}
	if !IsNil(o.VulnerabilityScanStatus) {
		toSerialize["vulnerability_scan_status"] = o.VulnerabilityScanStatus
	}
	return toSerialize, nil
}

type NullableModelHost struct {
	value *ModelHost
	isSet bool
}

func (v NullableModelHost) Get() *ModelHost {
	return v.value
}

func (v *NullableModelHost) Set(val *ModelHost) {
	v.value = val
	v.isSet = true
}

func (v NullableModelHost) IsSet() bool {
	return v.isSet
}

func (v *NullableModelHost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelHost(val *ModelHost) *NullableModelHost {
	return &NullableModelHost{value: val, isSet: true}
}

func (v NullableModelHost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelHost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


