/*
Deepfence ThreatMapper

Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.

API version: v3.0.0
Contact: community@deepfence.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ModelRulesActionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelRulesActionRequest{}

// ModelRulesActionRequest struct for ModelRulesActionRequest
type ModelRulesActionRequest struct {
	RuleIds []string `json:"rule_ids"`
}

type _ModelRulesActionRequest ModelRulesActionRequest

// NewModelRulesActionRequest instantiates a new ModelRulesActionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelRulesActionRequest(ruleIds []string) *ModelRulesActionRequest {
	this := ModelRulesActionRequest{}
	this.RuleIds = ruleIds
	return &this
}

// NewModelRulesActionRequestWithDefaults instantiates a new ModelRulesActionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelRulesActionRequestWithDefaults() *ModelRulesActionRequest {
	this := ModelRulesActionRequest{}
	return &this
}

// GetRuleIds returns the RuleIds field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *ModelRulesActionRequest) GetRuleIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.RuleIds
}

// GetRuleIdsOk returns a tuple with the RuleIds field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelRulesActionRequest) GetRuleIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.RuleIds) {
		return nil, false
	}
	return o.RuleIds, true
}

// SetRuleIds sets field value
func (o *ModelRulesActionRequest) SetRuleIds(v []string) {
	o.RuleIds = v
}

func (o ModelRulesActionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelRulesActionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.RuleIds != nil {
		toSerialize["rule_ids"] = o.RuleIds
	}
	return toSerialize, nil
}

func (o *ModelRulesActionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rule_ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelRulesActionRequest := _ModelRulesActionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModelRulesActionRequest)

	if err != nil {
		return err
	}

	*o = ModelRulesActionRequest(varModelRulesActionRequest)

	return err
}

type NullableModelRulesActionRequest struct {
	value *ModelRulesActionRequest
	isSet bool
}

func (v NullableModelRulesActionRequest) Get() *ModelRulesActionRequest {
	return v.value
}

func (v *NullableModelRulesActionRequest) Set(val *ModelRulesActionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModelRulesActionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModelRulesActionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelRulesActionRequest(val *ModelRulesActionRequest) *NullableModelRulesActionRequest {
	return &NullableModelRulesActionRequest{value: val, isSet: true}
}

func (v NullableModelRulesActionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelRulesActionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


